# Generated by Django 2.1.4 on 2018-12-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Art',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('f', 'F'), ('not enrolled', 'NOT ENROLLED')], default='not enrolled', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='History',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('f', 'F'), ('not enrolled', 'NOT ENROLLED')], default='not enrolled', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='Literature',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('f', 'F'), ('not enrolled', 'NOT ENROLLED')], default='not enrolled', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='Math',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('f', 'F'), ('not enrolled', 'NOT ENROLLED')], default='not enrolled', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='Science',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('f', 'F'), ('not enrolled', 'NOT ENROLLED')], default='not enrolled', max_length=12),
        ),
    ]
