# Generated by Django 2.1.4 on 2019-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190109_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('prefer not to answer', 'Prefer Not to Answer'), ('non-binary', 'Non-binary/Gender Non-Conforming/Genderqueer'), ('male', 'Male'), ('female', 'Female')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='IEP_or_504_Plan',
            field=models.CharField(choices=[('iep and 504 plan', 'IEP and 504 Plan'), ('none', 'None'), ('iep', 'IEP'), ('504', '504 Plan')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Race',
            field=models.CharField(choices=[('black', 'Black or African American'), ('asian', 'Asian'), ('latinx', 'Latinx'), ('white', 'White'), ('amerindian', 'American Indian or Alaska Native'), ('hawaiian or pacific islander', 'Native Hawaiian or Other Pacific Islander'), ('mixed race', 'Mixed Race')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to answer', 'Prefer Not to Answer')], default='', max_length=12),
        ),
    ]
